spring:
  # 配置数据源信息
  datasource:
    dynamic:
      # 设置默认的数据源或数据源组，默认值即为master
      primary: master
      # 严格匹配数据库，默认不启用。未匹配到数据源时，true抛异常，false使用默认数据源
      strict: false
      datasource:
        # 主数据源，跟上面primary的值保持一致
        master:
          url: jdbc:mysql://172.16.5.203:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 'Mysql300654=-=3K4i%$'
        slave_1:
          url: jdbc:mysql://172.16.5.203:3306/mybatis_plus_1?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 'Mysql300654=-=3K4i%$'
mybatis-plus:
  type-aliases-package: com.atguigu.mybatisplus.pojo